### ISSUE TITLE
App crashing Upon Install

### ISSUE THREAD

**Issue by npmaharaj1** [Abdelilah27/Uptime-Kuma-Mobile-Version#1]
I used Android Code Studio to compile the app and everything works except for when I login. The app stops then exits.

**Comment by Abdelilah27** [comment]
It sounds like you're having an issue with the login feature of the app. If possible, please provide the logcat output from the Android Studio console when the app crashes during login. This will help me to better understand the issue and assist you in resolving it.

**Comment by npmaharaj1** [comment]
It seems to suddenly work now, I just left it for a bit....

**Comment by Abdelilah27** [comment]
Thank you for bringing this to my attention
